// Code generated by protoc-gen-go.
// source: simple.proto
// DO NOT EDIT!

/*
Package simple is a generated protocol buffer package.

It is generated from these files:
	simple.proto

It has these top-level messages:
	Req
	Res
*/
package simple

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Req struct {
	Int32Field    int32   `protobuf:"varint,1,opt,name=int32field" json:"int32field,omitempty"`
	Int64Field    int64   `protobuf:"varint,2,opt,name=int64field" json:"int64field,omitempty"`
	Floatfield    float32 `protobuf:"fixed32,3,opt,name=floatfield" json:"floatfield,omitempty"`
	Doublefield   float64 `protobuf:"fixed64,4,opt,name=doublefield" json:"doublefield,omitempty"`
	Uint32Field   uint32  `protobuf:"varint,5,opt,name=uint32field" json:"uint32field,omitempty"`
	Uint64Field   uint64  `protobuf:"varint,6,opt,name=uint64field" json:"uint64field,omitempty"`
	Sint32Field   int32   `protobuf:"zigzag32,7,opt,name=sint32field" json:"sint32field,omitempty"`
	Sint64Field   int64   `protobuf:"zigzag64,8,opt,name=sint64field" json:"sint64field,omitempty"`
	Fixed32Field  uint32  `protobuf:"fixed32,9,opt,name=fixed32field" json:"fixed32field,omitempty"`
	Fixed64Field  uint64  `protobuf:"fixed64,10,opt,name=fixed64field" json:"fixed64field,omitempty"`
	Sfixed32Field int32   `protobuf:"fixed32,11,opt,name=sfixed32field" json:"sfixed32field,omitempty"`
	Sfixed64Field int64   `protobuf:"fixed64,12,opt,name=sfixed64field" json:"sfixed64field,omitempty"`
	Boolfield     bool    `protobuf:"varint,13,opt,name=boolfield" json:"boolfield,omitempty"`
	Stringfield   string  `protobuf:"bytes,14,opt,name=stringfield" json:"stringfield,omitempty"`
	Bytesfield    []byte  `protobuf:"bytes,15,opt,name=bytesfield,proto3" json:"bytesfield,omitempty"`
	Int32Repeated []int32 `protobuf:"varint,16,rep,packed,name=int32Repeated" json:"int32Repeated,omitempty"`
}

func (m *Req) Reset()                    { *m = Req{} }
func (m *Req) String() string            { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()               {}
func (*Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Req) GetInt32Field() int32 {
	if m != nil {
		return m.Int32Field
	}
	return 0
}

func (m *Req) GetInt64Field() int64 {
	if m != nil {
		return m.Int64Field
	}
	return 0
}

func (m *Req) GetFloatfield() float32 {
	if m != nil {
		return m.Floatfield
	}
	return 0
}

func (m *Req) GetDoublefield() float64 {
	if m != nil {
		return m.Doublefield
	}
	return 0
}

func (m *Req) GetUint32Field() uint32 {
	if m != nil {
		return m.Uint32Field
	}
	return 0
}

func (m *Req) GetUint64Field() uint64 {
	if m != nil {
		return m.Uint64Field
	}
	return 0
}

func (m *Req) GetSint32Field() int32 {
	if m != nil {
		return m.Sint32Field
	}
	return 0
}

func (m *Req) GetSint64Field() int64 {
	if m != nil {
		return m.Sint64Field
	}
	return 0
}

func (m *Req) GetFixed32Field() uint32 {
	if m != nil {
		return m.Fixed32Field
	}
	return 0
}

func (m *Req) GetFixed64Field() uint64 {
	if m != nil {
		return m.Fixed64Field
	}
	return 0
}

func (m *Req) GetSfixed32Field() int32 {
	if m != nil {
		return m.Sfixed32Field
	}
	return 0
}

func (m *Req) GetSfixed64Field() int64 {
	if m != nil {
		return m.Sfixed64Field
	}
	return 0
}

func (m *Req) GetBoolfield() bool {
	if m != nil {
		return m.Boolfield
	}
	return false
}

func (m *Req) GetStringfield() string {
	if m != nil {
		return m.Stringfield
	}
	return ""
}

func (m *Req) GetBytesfield() []byte {
	if m != nil {
		return m.Bytesfield
	}
	return nil
}

func (m *Req) GetInt32Repeated() []int32 {
	if m != nil {
		return m.Int32Repeated
	}
	return nil
}

type Res struct {
	Int32Field    int32   `protobuf:"varint,1,opt,name=int32field" json:"int32field,omitempty"`
	Int64Field    int64   `protobuf:"varint,2,opt,name=int64field" json:"int64field,omitempty"`
	Floatfield    float32 `protobuf:"fixed32,3,opt,name=floatfield" json:"floatfield,omitempty"`
	Doublefield   float64 `protobuf:"fixed64,4,opt,name=doublefield" json:"doublefield,omitempty"`
	Uint32Field   uint32  `protobuf:"varint,5,opt,name=uint32field" json:"uint32field,omitempty"`
	Uint64Field   uint64  `protobuf:"varint,6,opt,name=uint64field" json:"uint64field,omitempty"`
	Sint32Field   int32   `protobuf:"zigzag32,7,opt,name=sint32field" json:"sint32field,omitempty"`
	Sint64Field   int64   `protobuf:"zigzag64,8,opt,name=sint64field" json:"sint64field,omitempty"`
	Fixed32Field  uint32  `protobuf:"fixed32,9,opt,name=fixed32field" json:"fixed32field,omitempty"`
	Fixed64Field  uint64  `protobuf:"fixed64,10,opt,name=fixed64field" json:"fixed64field,omitempty"`
	Sfixed32Field int32   `protobuf:"fixed32,11,opt,name=sfixed32field" json:"sfixed32field,omitempty"`
	Sfixed64Field int64   `protobuf:"fixed64,12,opt,name=sfixed64field" json:"sfixed64field,omitempty"`
	Boolfield     bool    `protobuf:"varint,13,opt,name=boolfield" json:"boolfield,omitempty"`
	Stringfield   string  `protobuf:"bytes,14,opt,name=stringfield" json:"stringfield,omitempty"`
	Bytesfield    []byte  `protobuf:"bytes,15,opt,name=bytesfield,proto3" json:"bytesfield,omitempty"`
	Int32Repeated []int32 `protobuf:"varint,16,rep,packed,name=int32Repeated" json:"int32Repeated,omitempty"`
}

func (m *Res) Reset()                    { *m = Res{} }
func (m *Res) String() string            { return proto.CompactTextString(m) }
func (*Res) ProtoMessage()               {}
func (*Res) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Res) GetInt32Field() int32 {
	if m != nil {
		return m.Int32Field
	}
	return 0
}

func (m *Res) GetInt64Field() int64 {
	if m != nil {
		return m.Int64Field
	}
	return 0
}

func (m *Res) GetFloatfield() float32 {
	if m != nil {
		return m.Floatfield
	}
	return 0
}

func (m *Res) GetDoublefield() float64 {
	if m != nil {
		return m.Doublefield
	}
	return 0
}

func (m *Res) GetUint32Field() uint32 {
	if m != nil {
		return m.Uint32Field
	}
	return 0
}

func (m *Res) GetUint64Field() uint64 {
	if m != nil {
		return m.Uint64Field
	}
	return 0
}

func (m *Res) GetSint32Field() int32 {
	if m != nil {
		return m.Sint32Field
	}
	return 0
}

func (m *Res) GetSint64Field() int64 {
	if m != nil {
		return m.Sint64Field
	}
	return 0
}

func (m *Res) GetFixed32Field() uint32 {
	if m != nil {
		return m.Fixed32Field
	}
	return 0
}

func (m *Res) GetFixed64Field() uint64 {
	if m != nil {
		return m.Fixed64Field
	}
	return 0
}

func (m *Res) GetSfixed32Field() int32 {
	if m != nil {
		return m.Sfixed32Field
	}
	return 0
}

func (m *Res) GetSfixed64Field() int64 {
	if m != nil {
		return m.Sfixed64Field
	}
	return 0
}

func (m *Res) GetBoolfield() bool {
	if m != nil {
		return m.Boolfield
	}
	return false
}

func (m *Res) GetStringfield() string {
	if m != nil {
		return m.Stringfield
	}
	return ""
}

func (m *Res) GetBytesfield() []byte {
	if m != nil {
		return m.Bytesfield
	}
	return nil
}

func (m *Res) GetInt32Repeated() []int32 {
	if m != nil {
		return m.Int32Repeated
	}
	return nil
}

func init() {
	proto.RegisterType((*Req)(nil), "simple.Req")
	proto.RegisterType((*Res)(nil), "simple.Res")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Simple service

type SimpleClient interface {
	Test(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
}

type simpleClient struct {
	cc *grpc.ClientConn
}

func NewSimpleClient(cc *grpc.ClientConn) SimpleClient {
	return &simpleClient{cc}
}

func (c *simpleClient) Test(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := grpc.Invoke(ctx, "/simple.Simple/Test", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Simple service

type SimpleServer interface {
	Test(context.Context, *Req) (*Res, error)
}

func RegisterSimpleServer(s *grpc.Server, srv SimpleServer) {
	s.RegisterService(&_Simple_serviceDesc, srv)
}

func _Simple_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simple.Simple/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleServer).Test(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _Simple_serviceDesc = grpc.ServiceDesc{
	ServiceName: "simple.Simple",
	HandlerType: (*SimpleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _Simple_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "simple.proto",
}

func init() { proto.RegisterFile("simple.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xec, 0x94, 0x41, 0x6e, 0xea, 0x30,
	0x10, 0x86, 0x35, 0x24, 0x04, 0x30, 0xe1, 0xc1, 0xf3, 0x0a, 0x55, 0x55, 0x35, 0x42, 0x5d, 0x8c,
	0xba, 0x60, 0x01, 0x55, 0x0f, 0x32, 0xed, 0x05, 0x88, 0x62, 0xaa, 0x48, 0x29, 0x01, 0x6c, 0xa4,
	0xf6, 0x48, 0xbd, 0x65, 0x95, 0x38, 0x2e, 0xe3, 0x55, 0x2f, 0xc0, 0xd2, 0xdf, 0xff, 0xe9, 0xd7,
	0x40, 0x46, 0xa3, 0x72, 0x5b, 0x7d, 0x1c, 0x6b, 0xb3, 0x3e, 0x9e, 0x1b, 0xd7, 0xe8, 0xcc, 0xbf,
	0x56, 0xdf, 0xa9, 0x4a, 0xd8, 0x9c, 0xf4, 0x83, 0x52, 0xd5, 0xc1, 0x6d, 0x37, 0xfb, 0xca, 0xd4,
	0xe5, 0x12, 0x10, 0x68, 0xc8, 0x82, 0xf4, 0xf9, 0xcb, 0xb3, 0xcf, 0x07, 0x08, 0x94, 0xb0, 0x20,
	0x6d, 0xbe, 0xaf, 0x9b, 0x9d, 0xf3, 0x79, 0x82, 0x40, 0x03, 0x16, 0x44, 0xa3, 0x9a, 0x96, 0xcd,
	0xa5, 0xa8, 0x8d, 0x17, 0x52, 0x04, 0x02, 0x96, 0xa8, 0x35, 0x2e, 0x62, 0x84, 0x21, 0x02, 0xcd,
	0x58, 0xa2, 0x60, 0x84, 0x21, 0x32, 0x04, 0x4a, 0x59, 0xa2, 0xd6, 0xb0, 0xa2, 0x63, 0x84, 0x40,
	0xff, 0x59, 0xa2, 0x60, 0x84, 0x8e, 0x31, 0x02, 0x69, 0x96, 0x48, 0xaf, 0x54, 0xbe, 0xaf, 0x3e,
	0x4d, 0x19, 0x4a, 0x26, 0x08, 0x34, 0xe2, 0x88, 0xfd, 0x3a, 0xa1, 0x46, 0x21, 0x50, 0xc6, 0x11,
	0xd3, 0x8f, 0x6a, 0x66, 0xa3, 0xa2, 0x29, 0x02, 0xcd, 0x39, 0x86, 0x57, 0x2b, 0x54, 0xe5, 0x08,
	0xb4, 0xe0, 0x18, 0xea, 0x7b, 0x35, 0x29, 0x9a, 0xa6, 0xf6, 0xc6, 0x0c, 0x81, 0xc6, 0x7c, 0x05,
	0xdd, 0x6f, 0x72, 0xe7, 0xea, 0xf0, 0xee, 0xf3, 0x7f, 0x08, 0x34, 0x61, 0x89, 0xda, 0xaf, 0x53,
	0x7c, 0x39, 0x63, 0xbd, 0x30, 0x47, 0xa0, 0x9c, 0x05, 0x69, 0xa7, 0xe8, 0xfe, 0x23, 0x36, 0x47,
	0xb3, 0x73, 0xa6, 0x5c, 0x2e, 0x30, 0xa1, 0x21, 0xc7, 0xb0, 0xdf, 0x15, 0x7b, 0xdb, 0x95, 0xdb,
	0xae, 0xfc, 0xb5, 0x2b, 0x9b, 0x27, 0x95, 0xbd, 0x76, 0x17, 0x46, 0xa3, 0x4a, 0xdf, 0x8c, 0x75,
	0x7a, 0xba, 0xee, 0x0f, 0x10, 0x9b, 0xd3, 0x9d, 0x78, 0xd8, 0x22, 0xeb, 0x4e, 0xd2, 0xf6, 0x27,
	0x00, 0x00, 0xff, 0xff, 0xe5, 0x5d, 0x8f, 0x4e, 0xa2, 0x04, 0x00, 0x00,
}
