// Code generated by protoc-gen-go.
// source: example.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	example.proto

It has these top-level messages:
	CreateUserReq
	CreateUserResp
	UserListReq
	UserListResp
	DeleteUserReq
	DeleteUserResp
	GetUserReq
	UserResp
	Req
	Res
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateUserReq struct {
}

func (m *CreateUserReq) Reset()                    { *m = CreateUserReq{} }
func (m *CreateUserReq) String() string            { return proto.CompactTextString(m) }
func (*CreateUserReq) ProtoMessage()               {}
func (*CreateUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateUserResp struct {
}

func (m *CreateUserResp) Reset()                    { *m = CreateUserResp{} }
func (m *CreateUserResp) String() string            { return proto.CompactTextString(m) }
func (*CreateUserResp) ProtoMessage()               {}
func (*CreateUserResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type UserListReq struct {
}

func (m *UserListReq) Reset()                    { *m = UserListReq{} }
func (m *UserListReq) String() string            { return proto.CompactTextString(m) }
func (*UserListReq) ProtoMessage()               {}
func (*UserListReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type UserListResp struct {
}

func (m *UserListResp) Reset()                    { *m = UserListResp{} }
func (m *UserListResp) String() string            { return proto.CompactTextString(m) }
func (*UserListResp) ProtoMessage()               {}
func (*UserListResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DeleteUserReq struct {
}

func (m *DeleteUserReq) Reset()                    { *m = DeleteUserReq{} }
func (m *DeleteUserReq) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserReq) ProtoMessage()               {}
func (*DeleteUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type DeleteUserResp struct {
}

func (m *DeleteUserResp) Reset()                    { *m = DeleteUserResp{} }
func (m *DeleteUserResp) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserResp) ProtoMessage()               {}
func (*DeleteUserResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type GetUserReq struct {
	FirstName string   `protobuf:"bytes,1,opt,name=firstName" json:"firstName,omitempty"`
	LastName  string   `protobuf:"bytes,2,opt,name=lastName" json:"lastName,omitempty"`
	Skills    []string `protobuf:"bytes,3,rep,name=skills" json:"skills,omitempty"`
	Ids       []int32  `protobuf:"varint,4,rep,packed,name=ids" json:"ids,omitempty"`
	Age       int32    `protobuf:"varint,5,opt,name=age" json:"age,omitempty"`
}

func (m *GetUserReq) Reset()                    { *m = GetUserReq{} }
func (m *GetUserReq) String() string            { return proto.CompactTextString(m) }
func (*GetUserReq) ProtoMessage()               {}
func (*GetUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetUserReq) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *GetUserReq) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *GetUserReq) GetSkills() []string {
	if m != nil {
		return m.Skills
	}
	return nil
}

func (m *GetUserReq) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *GetUserReq) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type UserResp struct {
	FirstName string `protobuf:"bytes,1,opt,name=firstName" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=lastName" json:"lastName,omitempty"`
	Active    bool   `protobuf:"varint,3,opt,name=active" json:"active,omitempty"`
	Age       int32  `protobuf:"varint,4,opt,name=age" json:"age,omitempty"`
	Skills    string `protobuf:"bytes,5,opt,name=skills" json:"skills,omitempty"`
}

func (m *UserResp) Reset()                    { *m = UserResp{} }
func (m *UserResp) String() string            { return proto.CompactTextString(m) }
func (*UserResp) ProtoMessage()               {}
func (*UserResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UserResp) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserResp) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserResp) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *UserResp) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserResp) GetSkills() string {
	if m != nil {
		return m.Skills
	}
	return ""
}

type Req struct {
	Int32Field    int32   `protobuf:"varint,1,opt,name=int32field" json:"int32field,omitempty"`
	Int64Field    int64   `protobuf:"varint,2,opt,name=int64field" json:"int64field,omitempty"`
	Floatfield    float32 `protobuf:"fixed32,3,opt,name=floatfield" json:"floatfield,omitempty"`
	Doublefield   float64 `protobuf:"fixed64,4,opt,name=doublefield" json:"doublefield,omitempty"`
	Uint32Field   uint32  `protobuf:"varint,5,opt,name=uint32field" json:"uint32field,omitempty"`
	Uint64Field   uint64  `protobuf:"varint,6,opt,name=uint64field" json:"uint64field,omitempty"`
	Sint32Field   int32   `protobuf:"zigzag32,7,opt,name=sint32field" json:"sint32field,omitempty"`
	Sint64Field   int64   `protobuf:"zigzag64,8,opt,name=sint64field" json:"sint64field,omitempty"`
	Fixed32Field  uint32  `protobuf:"fixed32,9,opt,name=fixed32field" json:"fixed32field,omitempty"`
	Fixed64Field  uint64  `protobuf:"fixed64,10,opt,name=fixed64field" json:"fixed64field,omitempty"`
	Sfixed32Field int32   `protobuf:"fixed32,11,opt,name=sfixed32field" json:"sfixed32field,omitempty"`
	Sfixed64Field int64   `protobuf:"fixed64,12,opt,name=sfixed64field" json:"sfixed64field,omitempty"`
	Boolfield     bool    `protobuf:"varint,13,opt,name=boolfield" json:"boolfield,omitempty"`
	Stringfield   string  `protobuf:"bytes,14,opt,name=stringfield" json:"stringfield,omitempty"`
	Bytesfield    []byte  `protobuf:"bytes,15,opt,name=bytesfield,proto3" json:"bytesfield,omitempty"`
	Int32Repeated []int32 `protobuf:"varint,16,rep,packed,name=int32Repeated" json:"int32Repeated,omitempty"`
}

func (m *Req) Reset()                    { *m = Req{} }
func (m *Req) String() string            { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()               {}
func (*Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Req) GetInt32Field() int32 {
	if m != nil {
		return m.Int32Field
	}
	return 0
}

func (m *Req) GetInt64Field() int64 {
	if m != nil {
		return m.Int64Field
	}
	return 0
}

func (m *Req) GetFloatfield() float32 {
	if m != nil {
		return m.Floatfield
	}
	return 0
}

func (m *Req) GetDoublefield() float64 {
	if m != nil {
		return m.Doublefield
	}
	return 0
}

func (m *Req) GetUint32Field() uint32 {
	if m != nil {
		return m.Uint32Field
	}
	return 0
}

func (m *Req) GetUint64Field() uint64 {
	if m != nil {
		return m.Uint64Field
	}
	return 0
}

func (m *Req) GetSint32Field() int32 {
	if m != nil {
		return m.Sint32Field
	}
	return 0
}

func (m *Req) GetSint64Field() int64 {
	if m != nil {
		return m.Sint64Field
	}
	return 0
}

func (m *Req) GetFixed32Field() uint32 {
	if m != nil {
		return m.Fixed32Field
	}
	return 0
}

func (m *Req) GetFixed64Field() uint64 {
	if m != nil {
		return m.Fixed64Field
	}
	return 0
}

func (m *Req) GetSfixed32Field() int32 {
	if m != nil {
		return m.Sfixed32Field
	}
	return 0
}

func (m *Req) GetSfixed64Field() int64 {
	if m != nil {
		return m.Sfixed64Field
	}
	return 0
}

func (m *Req) GetBoolfield() bool {
	if m != nil {
		return m.Boolfield
	}
	return false
}

func (m *Req) GetStringfield() string {
	if m != nil {
		return m.Stringfield
	}
	return ""
}

func (m *Req) GetBytesfield() []byte {
	if m != nil {
		return m.Bytesfield
	}
	return nil
}

func (m *Req) GetInt32Repeated() []int32 {
	if m != nil {
		return m.Int32Repeated
	}
	return nil
}

type Res struct {
	Int32Field    int32   `protobuf:"varint,1,opt,name=int32field" json:"int32field,omitempty"`
	Int64Field    int64   `protobuf:"varint,2,opt,name=int64field" json:"int64field,omitempty"`
	Floatfield    float32 `protobuf:"fixed32,3,opt,name=floatfield" json:"floatfield,omitempty"`
	Doublefield   float64 `protobuf:"fixed64,4,opt,name=doublefield" json:"doublefield,omitempty"`
	Uint32Field   uint32  `protobuf:"varint,5,opt,name=uint32field" json:"uint32field,omitempty"`
	Uint64Field   uint64  `protobuf:"varint,6,opt,name=uint64field" json:"uint64field,omitempty"`
	Sint32Field   int32   `protobuf:"zigzag32,7,opt,name=sint32field" json:"sint32field,omitempty"`
	Sint64Field   int64   `protobuf:"zigzag64,8,opt,name=sint64field" json:"sint64field,omitempty"`
	Fixed32Field  uint32  `protobuf:"fixed32,9,opt,name=fixed32field" json:"fixed32field,omitempty"`
	Fixed64Field  uint64  `protobuf:"fixed64,10,opt,name=fixed64field" json:"fixed64field,omitempty"`
	Sfixed32Field int32   `protobuf:"fixed32,11,opt,name=sfixed32field" json:"sfixed32field,omitempty"`
	Sfixed64Field int64   `protobuf:"fixed64,12,opt,name=sfixed64field" json:"sfixed64field,omitempty"`
	Boolfield     bool    `protobuf:"varint,13,opt,name=boolfield" json:"boolfield,omitempty"`
	Stringfield   string  `protobuf:"bytes,14,opt,name=stringfield" json:"stringfield,omitempty"`
	Bytesfield    []byte  `protobuf:"bytes,15,opt,name=bytesfield,proto3" json:"bytesfield,omitempty"`
	Int32Repeated []int32 `protobuf:"varint,16,rep,packed,name=int32Repeated" json:"int32Repeated,omitempty"`
}

func (m *Res) Reset()                    { *m = Res{} }
func (m *Res) String() string            { return proto.CompactTextString(m) }
func (*Res) ProtoMessage()               {}
func (*Res) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Res) GetInt32Field() int32 {
	if m != nil {
		return m.Int32Field
	}
	return 0
}

func (m *Res) GetInt64Field() int64 {
	if m != nil {
		return m.Int64Field
	}
	return 0
}

func (m *Res) GetFloatfield() float32 {
	if m != nil {
		return m.Floatfield
	}
	return 0
}

func (m *Res) GetDoublefield() float64 {
	if m != nil {
		return m.Doublefield
	}
	return 0
}

func (m *Res) GetUint32Field() uint32 {
	if m != nil {
		return m.Uint32Field
	}
	return 0
}

func (m *Res) GetUint64Field() uint64 {
	if m != nil {
		return m.Uint64Field
	}
	return 0
}

func (m *Res) GetSint32Field() int32 {
	if m != nil {
		return m.Sint32Field
	}
	return 0
}

func (m *Res) GetSint64Field() int64 {
	if m != nil {
		return m.Sint64Field
	}
	return 0
}

func (m *Res) GetFixed32Field() uint32 {
	if m != nil {
		return m.Fixed32Field
	}
	return 0
}

func (m *Res) GetFixed64Field() uint64 {
	if m != nil {
		return m.Fixed64Field
	}
	return 0
}

func (m *Res) GetSfixed32Field() int32 {
	if m != nil {
		return m.Sfixed32Field
	}
	return 0
}

func (m *Res) GetSfixed64Field() int64 {
	if m != nil {
		return m.Sfixed64Field
	}
	return 0
}

func (m *Res) GetBoolfield() bool {
	if m != nil {
		return m.Boolfield
	}
	return false
}

func (m *Res) GetStringfield() string {
	if m != nil {
		return m.Stringfield
	}
	return ""
}

func (m *Res) GetBytesfield() []byte {
	if m != nil {
		return m.Bytesfield
	}
	return nil
}

func (m *Res) GetInt32Repeated() []int32 {
	if m != nil {
		return m.Int32Repeated
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateUserReq)(nil), "pb.CreateUserReq")
	proto.RegisterType((*CreateUserResp)(nil), "pb.CreateUserResp")
	proto.RegisterType((*UserListReq)(nil), "pb.UserListReq")
	proto.RegisterType((*UserListResp)(nil), "pb.UserListResp")
	proto.RegisterType((*DeleteUserReq)(nil), "pb.DeleteUserReq")
	proto.RegisterType((*DeleteUserResp)(nil), "pb.DeleteUserResp")
	proto.RegisterType((*GetUserReq)(nil), "pb.GetUserReq")
	proto.RegisterType((*UserResp)(nil), "pb.UserResp")
	proto.RegisterType((*Req)(nil), "pb.Req")
	proto.RegisterType((*Res)(nil), "pb.Res")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Example service

type ExampleClient interface {
	// rpc Test(Req) returns (Res);
	GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*UserResp, error)
	CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error)
	UserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error)
	DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserResp, error)
}

type exampleClient struct {
	cc *grpc.ClientConn
}

func NewExampleClient(cc *grpc.ClientConn) ExampleClient {
	return &exampleClient{cc}
}

func (c *exampleClient) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*UserResp, error) {
	out := new(UserResp)
	err := grpc.Invoke(ctx, "/pb.Example/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error) {
	out := new(CreateUserResp)
	err := grpc.Invoke(ctx, "/pb.Example/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) UserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error) {
	out := new(UserListResp)
	err := grpc.Invoke(ctx, "/pb.Example/UserList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserResp, error) {
	out := new(DeleteUserResp)
	err := grpc.Invoke(ctx, "/pb.Example/DeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Example service

type ExampleServer interface {
	// rpc Test(Req) returns (Res);
	GetUser(context.Context, *GetUserReq) (*UserResp, error)
	CreateUser(context.Context, *CreateUserReq) (*CreateUserResp, error)
	UserList(context.Context, *UserListReq) (*UserListResp, error)
	DeleteUser(context.Context, *DeleteUserReq) (*DeleteUserResp, error)
}

func RegisterExampleServer(s *grpc.Server, srv ExampleServer) {
	s.RegisterService(&_Example_serviceDesc, srv)
}

func _Example_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Example/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).GetUser(ctx, req.(*GetUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Example/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).CreateUser(ctx, req.(*CreateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_UserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Example/UserList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UserList(ctx, req.(*UserListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Example/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).DeleteUser(ctx, req.(*DeleteUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Example_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Example",
	HandlerType: (*ExampleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _Example_GetUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _Example_CreateUser_Handler,
		},
		{
			MethodName: "UserList",
			Handler:    _Example_UserList_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _Example_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example.proto",
}

func init() { proto.RegisterFile("example.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xec, 0x95, 0xbf, 0x8e, 0xd3, 0x40,
	0x10, 0xc6, 0xb5, 0xe7, 0xfc, 0x9d, 0xd8, 0x89, 0x6f, 0x0b, 0x64, 0x45, 0x08, 0xad, 0x2c, 0x24,
	0xb6, 0x21, 0xc5, 0x05, 0xf1, 0x02, 0x80, 0x68, 0x10, 0xc5, 0x48, 0x3c, 0x80, 0x8d, 0x37, 0x91,
	0x85, 0xef, 0x6c, 0xbc, 0x7b, 0xe8, 0x68, 0x29, 0x78, 0x17, 0x9e, 0x85, 0x97, 0x42, 0xe3, 0xf5,
	0xc6, 0xbb, 0x34, 0x14, 0xb4, 0xd7, 0x79, 0x7e, 0xf3, 0x69, 0xe6, 0x8b, 0x3d, 0x99, 0x81, 0x44,
	0x3d, 0x14, 0xb7, 0x5d, 0xa3, 0x0e, 0x5d, 0xdf, 0x9a, 0x96, 0x5f, 0x75, 0x65, 0xbe, 0x83, 0xe4,
	0x4d, 0xaf, 0x0a, 0xa3, 0x3e, 0x69, 0xd5, 0xa3, 0xfa, 0x9a, 0xa7, 0xb0, 0xf5, 0x81, 0xee, 0xf2,
	0x04, 0x36, 0xf4, 0xfc, 0xa1, 0xd6, 0x86, 0x04, 0x5b, 0x88, 0xa7, 0x50, 0x77, 0x54, 0xe1, 0xad,
	0x6a, 0x54, 0x50, 0xc1, 0x07, 0xba, 0xcb, 0x7f, 0x30, 0x80, 0xf7, 0xca, 0x8c, 0x02, 0xfe, 0x14,
	0xd6, 0xa7, 0xba, 0xd7, 0xe6, 0x63, 0x71, 0xab, 0x32, 0x26, 0x98, 0x5c, 0xe3, 0x04, 0xf8, 0x1e,
	0x56, 0x4d, 0x31, 0x26, 0xaf, 0x86, 0xe4, 0x25, 0xe6, 0x4f, 0x60, 0xa1, 0xbf, 0xd4, 0x4d, 0xa3,
	0xb3, 0x48, 0x44, 0x72, 0x8d, 0x63, 0xc4, 0x53, 0x88, 0xea, 0x4a, 0x67, 0x33, 0x11, 0xc9, 0x39,
	0xd2, 0x23, 0x91, 0xe2, 0xac, 0xb2, 0xb9, 0x60, 0x44, 0x8a, 0xb3, 0xca, 0x7f, 0x32, 0x58, 0x39,
	0x47, 0xff, 0x67, 0xa1, 0xf8, 0x6c, 0xea, 0x6f, 0x2a, 0x8b, 0x04, 0x93, 0x2b, 0x1c, 0x23, 0xd7,
	0x70, 0x76, 0x69, 0xe8, 0x99, 0x9d, 0x0f, 0x35, 0xc6, 0x28, 0xff, 0x35, 0x83, 0x88, 0x5e, 0xc3,
	0x33, 0x80, 0xfa, 0xce, 0x1c, 0x6f, 0x4e, 0xb5, 0x6a, 0xaa, 0xc1, 0xc4, 0x1c, 0x3d, 0x32, 0xe6,
	0x5f, 0xbf, 0xb2, 0x79, 0xf2, 0x11, 0xa1, 0x47, 0x28, 0x7f, 0x6a, 0xda, 0xc2, 0xd8, 0x3c, 0xb9,
	0xb9, 0x42, 0x8f, 0x70, 0x01, 0x9b, 0xaa, 0xbd, 0x2f, 0x1b, 0x65, 0x05, 0xe4, 0x8c, 0xa1, 0x8f,
	0x48, 0x71, 0xef, 0x59, 0x20, 0x9b, 0x09, 0xfa, 0xc8, 0x29, 0x9c, 0x89, 0x85, 0x60, 0x72, 0x86,
	0x3e, 0x22, 0x85, 0xf6, 0x6a, 0x2c, 0x05, 0x93, 0xd7, 0xe8, 0x23, 0xa7, 0x70, 0x35, 0x56, 0x82,
	0x49, 0x8e, 0x3e, 0xe2, 0x39, 0xc4, 0xa7, 0xfa, 0x41, 0x55, 0xae, 0xc8, 0x5a, 0x30, 0xb9, 0xc4,
	0x80, 0x5d, 0x34, 0xae, 0x0c, 0x08, 0x26, 0x17, 0x18, 0x30, 0xfe, 0x1c, 0x12, 0x1d, 0x14, 0xda,
	0x08, 0x26, 0x77, 0x18, 0xc2, 0x49, 0xe5, 0x4a, 0xc5, 0x82, 0xc9, 0x14, 0x43, 0x48, 0x13, 0x52,
	0xb6, 0x6d, 0x63, 0x15, 0xc9, 0xf0, 0xa9, 0x27, 0x30, 0xfc, 0x26, 0xd3, 0xd7, 0x77, 0x67, 0x9b,
	0xdf, 0x0e, 0x1f, 0xd8, 0x47, 0xf4, 0x75, 0xca, 0xef, 0x46, 0x69, 0x2b, 0xd8, 0x09, 0x26, 0x63,
	0xf4, 0x08, 0xb9, 0x18, 0xde, 0x11, 0xaa, 0x8e, 0xfe, 0x6d, 0x55, 0x96, 0x0e, 0xc3, 0x1b, 0xc2,
	0x71, 0x56, 0xf4, 0xe3, 0xac, 0x3c, 0xce, 0xca, 0xbf, 0x66, 0xe5, 0xe6, 0x37, 0x83, 0xe5, 0x3b,
	0xbb, 0xe0, 0xf9, 0x0b, 0x58, 0x8e, 0x0b, 0x97, 0x6f, 0x0f, 0x5d, 0x79, 0x98, 0xb6, 0xef, 0x3e,
	0xa6, 0xf8, 0xb2, 0x08, 0x8f, 0x00, 0xd3, 0xba, 0xe7, 0xd7, 0x94, 0x0b, 0xee, 0xc1, 0x9e, 0xff,
	0x8d, 0x74, 0xc7, 0x5f, 0xda, 0x4d, 0x4a, 0x27, 0x80, 0xef, 0x5c, 0xb9, 0xf1, 0x3e, 0xec, 0xd3,
	0x10, 0xd8, 0x1e, 0xd3, 0x41, 0xb0, 0x3d, 0x82, 0x8b, 0x61, 0x7b, 0x84, 0x37, 0xa3, 0x5c, 0x0c,
	0x37, 0xea, 0xf8, 0x27, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xf2, 0x92, 0x77, 0xb4, 0x06, 0x00, 0x00,
}
