// Code generated by protoc-gen-go.
// source: example.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	example.proto

It has these top-level messages:
	Req
	Res
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Req struct {
	Int32Field    int32   `protobuf:"varint,1,opt,name=int32field" json:"int32field,omitempty"`
	Int64Field    int64   `protobuf:"varint,2,opt,name=int64field" json:"int64field,omitempty"`
	Floatfield    float32 `protobuf:"fixed32,3,opt,name=floatfield" json:"floatfield,omitempty"`
	Doublefield   float64 `protobuf:"fixed64,4,opt,name=doublefield" json:"doublefield,omitempty"`
	Uint32Field   uint32  `protobuf:"varint,5,opt,name=uint32field" json:"uint32field,omitempty"`
	Uint64Field   uint64  `protobuf:"varint,6,opt,name=uint64field" json:"uint64field,omitempty"`
	Sint32Field   int32   `protobuf:"zigzag32,7,opt,name=sint32field" json:"sint32field,omitempty"`
	Sint64Field   int64   `protobuf:"zigzag64,8,opt,name=sint64field" json:"sint64field,omitempty"`
	Fixed32Field  uint32  `protobuf:"fixed32,9,opt,name=fixed32field" json:"fixed32field,omitempty"`
	Fixed64Field  uint64  `protobuf:"fixed64,10,opt,name=fixed64field" json:"fixed64field,omitempty"`
	Sfixed32Field int32   `protobuf:"fixed32,11,opt,name=sfixed32field" json:"sfixed32field,omitempty"`
	Sfixed64Field int64   `protobuf:"fixed64,12,opt,name=sfixed64field" json:"sfixed64field,omitempty"`
	Boolfield     bool    `protobuf:"varint,13,opt,name=boolfield" json:"boolfield,omitempty"`
	Stringfield   string  `protobuf:"bytes,14,opt,name=stringfield" json:"stringfield,omitempty"`
	Bytesfield    []byte  `protobuf:"bytes,15,opt,name=bytesfield,proto3" json:"bytesfield,omitempty"`
}

func (m *Req) Reset()                    { *m = Req{} }
func (m *Req) String() string            { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()               {}
func (*Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Req) GetInt32Field() int32 {
	if m != nil {
		return m.Int32Field
	}
	return 0
}

func (m *Req) GetInt64Field() int64 {
	if m != nil {
		return m.Int64Field
	}
	return 0
}

func (m *Req) GetFloatfield() float32 {
	if m != nil {
		return m.Floatfield
	}
	return 0
}

func (m *Req) GetDoublefield() float64 {
	if m != nil {
		return m.Doublefield
	}
	return 0
}

func (m *Req) GetUint32Field() uint32 {
	if m != nil {
		return m.Uint32Field
	}
	return 0
}

func (m *Req) GetUint64Field() uint64 {
	if m != nil {
		return m.Uint64Field
	}
	return 0
}

func (m *Req) GetSint32Field() int32 {
	if m != nil {
		return m.Sint32Field
	}
	return 0
}

func (m *Req) GetSint64Field() int64 {
	if m != nil {
		return m.Sint64Field
	}
	return 0
}

func (m *Req) GetFixed32Field() uint32 {
	if m != nil {
		return m.Fixed32Field
	}
	return 0
}

func (m *Req) GetFixed64Field() uint64 {
	if m != nil {
		return m.Fixed64Field
	}
	return 0
}

func (m *Req) GetSfixed32Field() int32 {
	if m != nil {
		return m.Sfixed32Field
	}
	return 0
}

func (m *Req) GetSfixed64Field() int64 {
	if m != nil {
		return m.Sfixed64Field
	}
	return 0
}

func (m *Req) GetBoolfield() bool {
	if m != nil {
		return m.Boolfield
	}
	return false
}

func (m *Req) GetStringfield() string {
	if m != nil {
		return m.Stringfield
	}
	return ""
}

func (m *Req) GetBytesfield() []byte {
	if m != nil {
		return m.Bytesfield
	}
	return nil
}

type Res struct {
	Int32Field    int32   `protobuf:"varint,1,opt,name=int32field" json:"int32field,omitempty"`
	Int64Field    int64   `protobuf:"varint,2,opt,name=int64field" json:"int64field,omitempty"`
	Floatfield    float32 `protobuf:"fixed32,3,opt,name=floatfield" json:"floatfield,omitempty"`
	Doublefield   float64 `protobuf:"fixed64,4,opt,name=doublefield" json:"doublefield,omitempty"`
	Uint32Field   uint32  `protobuf:"varint,5,opt,name=uint32field" json:"uint32field,omitempty"`
	Uint64Field   uint64  `protobuf:"varint,6,opt,name=uint64field" json:"uint64field,omitempty"`
	Sint32Field   int32   `protobuf:"zigzag32,7,opt,name=sint32field" json:"sint32field,omitempty"`
	Sint64Field   int64   `protobuf:"zigzag64,8,opt,name=sint64field" json:"sint64field,omitempty"`
	Fixed32Field  uint32  `protobuf:"fixed32,9,opt,name=fixed32field" json:"fixed32field,omitempty"`
	Fixed64Field  uint64  `protobuf:"fixed64,10,opt,name=fixed64field" json:"fixed64field,omitempty"`
	Sfixed32Field int32   `protobuf:"fixed32,11,opt,name=sfixed32field" json:"sfixed32field,omitempty"`
	Sfixed64Field int64   `protobuf:"fixed64,12,opt,name=sfixed64field" json:"sfixed64field,omitempty"`
	Boolfield     bool    `protobuf:"varint,13,opt,name=boolfield" json:"boolfield,omitempty"`
	Stringfield   string  `protobuf:"bytes,14,opt,name=stringfield" json:"stringfield,omitempty"`
	Bytesfield    []byte  `protobuf:"bytes,15,opt,name=bytesfield,proto3" json:"bytesfield,omitempty"`
}

func (m *Res) Reset()                    { *m = Res{} }
func (m *Res) String() string            { return proto.CompactTextString(m) }
func (*Res) ProtoMessage()               {}
func (*Res) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Res) GetInt32Field() int32 {
	if m != nil {
		return m.Int32Field
	}
	return 0
}

func (m *Res) GetInt64Field() int64 {
	if m != nil {
		return m.Int64Field
	}
	return 0
}

func (m *Res) GetFloatfield() float32 {
	if m != nil {
		return m.Floatfield
	}
	return 0
}

func (m *Res) GetDoublefield() float64 {
	if m != nil {
		return m.Doublefield
	}
	return 0
}

func (m *Res) GetUint32Field() uint32 {
	if m != nil {
		return m.Uint32Field
	}
	return 0
}

func (m *Res) GetUint64Field() uint64 {
	if m != nil {
		return m.Uint64Field
	}
	return 0
}

func (m *Res) GetSint32Field() int32 {
	if m != nil {
		return m.Sint32Field
	}
	return 0
}

func (m *Res) GetSint64Field() int64 {
	if m != nil {
		return m.Sint64Field
	}
	return 0
}

func (m *Res) GetFixed32Field() uint32 {
	if m != nil {
		return m.Fixed32Field
	}
	return 0
}

func (m *Res) GetFixed64Field() uint64 {
	if m != nil {
		return m.Fixed64Field
	}
	return 0
}

func (m *Res) GetSfixed32Field() int32 {
	if m != nil {
		return m.Sfixed32Field
	}
	return 0
}

func (m *Res) GetSfixed64Field() int64 {
	if m != nil {
		return m.Sfixed64Field
	}
	return 0
}

func (m *Res) GetBoolfield() bool {
	if m != nil {
		return m.Boolfield
	}
	return false
}

func (m *Res) GetStringfield() string {
	if m != nil {
		return m.Stringfield
	}
	return ""
}

func (m *Res) GetBytesfield() []byte {
	if m != nil {
		return m.Bytesfield
	}
	return nil
}

func init() {
	proto.RegisterType((*Req)(nil), "pb.Req")
	proto.RegisterType((*Res)(nil), "pb.Res")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Example service

type ExampleClient interface {
	Test(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
}

type exampleClient struct {
	cc *grpc.ClientConn
}

func NewExampleClient(cc *grpc.ClientConn) ExampleClient {
	return &exampleClient{cc}
}

func (c *exampleClient) Test(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := grpc.Invoke(ctx, "/pb.Example/Test", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Example service

type ExampleServer interface {
	Test(context.Context, *Req) (*Res, error)
}

func RegisterExampleServer(s *grpc.Server, srv ExampleServer) {
	s.RegisterService(&_Example_serviceDesc, srv)
}

func _Example_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Example/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).Test(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _Example_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Example",
	HandlerType: (*ExampleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _Example_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example.proto",
}

func init() { proto.RegisterFile("example.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xec, 0x94, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0x33, 0x50, 0x28, 0x2c, 0x54, 0x74, 0x4f, 0xc4, 0x18, 0x33, 0x41, 0x0f, 0x73, 0xe2,
	0x00, 0xc6, 0x37, 0xf0, 0x05, 0x26, 0xbe, 0x00, 0x1b, 0x16, 0xd3, 0xa4, 0xb2, 0x85, 0x5d, 0x12,
	0x3c, 0xfb, 0xe2, 0xa6, 0x6c, 0x57, 0xa6, 0xcf, 0xa0, 0xb7, 0xe6, 0xfb, 0xbf, 0xfc, 0x99, 0x66,
	0x27, 0xa3, 0x0a, 0x7b, 0xde, 0x7c, 0xd6, 0x95, 0x5d, 0xd6, 0x47, 0x17, 0x9c, 0xee, 0xd5, 0x66,
	0xf1, 0x9d, 0xa9, 0x3e, 0xdb, 0x83, 0x7e, 0x54, 0xaa, 0xdc, 0x87, 0xf5, 0x6a, 0x57, 0xda, 0x6a,
	0x3b, 0x07, 0x04, 0x1a, 0xb0, 0x20, 0x6d, 0xfe, 0xfa, 0x12, 0xf3, 0x1e, 0x02, 0xf5, 0x59, 0x90,
	0x26, 0xdf, 0x55, 0x6e, 0x13, 0x62, 0xde, 0x47, 0xa0, 0x1e, 0x0b, 0xa2, 0x51, 0x4d, 0xb6, 0xee,
	0x64, 0x2a, 0x1b, 0x85, 0x0c, 0x81, 0x80, 0x25, 0x6a, 0x8c, 0x93, 0x18, 0x61, 0x80, 0x40, 0x05,
	0x4b, 0x94, 0x8c, 0x34, 0xc4, 0x10, 0x81, 0x32, 0x96, 0xa8, 0x31, 0xbc, 0xe8, 0xc8, 0x11, 0xe8,
	0x8e, 0x25, 0x4a, 0x46, 0xea, 0x18, 0x21, 0x90, 0x66, 0x89, 0xf4, 0x42, 0x4d, 0x77, 0xe5, 0xd9,
	0x6e, 0x53, 0xc9, 0x18, 0x81, 0x72, 0xee, 0xb0, 0x5f, 0x27, 0xd5, 0x28, 0x04, 0x1a, 0x72, 0x87,
	0xe9, 0x67, 0x55, 0xf8, 0x4e, 0xd1, 0x04, 0x81, 0x66, 0xdc, 0x85, 0x57, 0x2b, 0x55, 0x4d, 0x11,
	0xe8, 0x96, 0xbb, 0x50, 0x3f, 0xa8, 0xb1, 0x71, 0xae, 0x8a, 0x46, 0x81, 0x40, 0x23, 0xbe, 0x82,
	0xcb, 0x3f, 0x85, 0x63, 0xb9, 0xff, 0x88, 0xf9, 0x0d, 0x02, 0x8d, 0x59, 0xa2, 0xe6, 0x75, 0xcc,
	0x57, 0xb0, 0x3e, 0x0a, 0x33, 0x04, 0x9a, 0xb2, 0x20, 0xed, 0x16, 0xf8, 0xff, 0x2d, 0xf8, 0xcb,
	0x5b, 0xb0, 0x7a, 0x52, 0xf9, 0x5b, 0x3c, 0x10, 0x7a, 0xae, 0xb2, 0x77, 0xeb, 0x83, 0xce, 0x97,
	0xb5, 0x59, 0xb2, 0x3d, 0xdc, 0xb7, 0x1f, 0xde, 0x0c, 0x2f, 0xb7, 0x63, 0xfd, 0x13, 0x00, 0x00,
	0xff, 0xff, 0x29, 0xa1, 0x10, 0x92, 0x4c, 0x04, 0x00, 0x00,
}
