// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package http_server is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	ReflectionResponse
	Reflection
	Error
	InvokeRequest
	InvokeResponse
*/
package http_server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReflectionResponse struct {
	// Types that are valid to be assigned to Response:
	//	*ReflectionResponse_Reflection
	//	*ReflectionResponse_Error
	Response isReflectionResponse_Response `protobuf_oneof:"response"`
}

func (m *ReflectionResponse) Reset()                    { *m = ReflectionResponse{} }
func (m *ReflectionResponse) String() string            { return proto.CompactTextString(m) }
func (*ReflectionResponse) ProtoMessage()               {}
func (*ReflectionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isReflectionResponse_Response interface {
	isReflectionResponse_Response()
}

type ReflectionResponse_Reflection struct {
	Reflection *Reflection `protobuf:"bytes,1,opt,name=reflection,oneof"`
}
type ReflectionResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,oneof"`
}

func (*ReflectionResponse_Reflection) isReflectionResponse_Response() {}
func (*ReflectionResponse_Error) isReflectionResponse_Response()      {}

func (m *ReflectionResponse) GetResponse() isReflectionResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *ReflectionResponse) GetReflection() *Reflection {
	if x, ok := m.GetResponse().(*ReflectionResponse_Reflection); ok {
		return x.Reflection
	}
	return nil
}

func (m *ReflectionResponse) GetError() *Error {
	if x, ok := m.GetResponse().(*ReflectionResponse_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ReflectionResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ReflectionResponse_OneofMarshaler, _ReflectionResponse_OneofUnmarshaler, _ReflectionResponse_OneofSizer, []interface{}{
		(*ReflectionResponse_Reflection)(nil),
		(*ReflectionResponse_Error)(nil),
	}
}

func _ReflectionResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ReflectionResponse)
	// response
	switch x := m.Response.(type) {
	case *ReflectionResponse_Reflection:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Reflection); err != nil {
			return err
		}
	case *ReflectionResponse_Error:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ReflectionResponse.Response has unexpected type %T", x)
	}
	return nil
}

func _ReflectionResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ReflectionResponse)
	switch tag {
	case 1: // response.reflection
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Reflection)
		err := b.DecodeMessage(msg)
		m.Response = &ReflectionResponse_Reflection{msg}
		return true, err
	case 2: // response.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Error)
		err := b.DecodeMessage(msg)
		m.Response = &ReflectionResponse_Error{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ReflectionResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ReflectionResponse)
	// response
	switch x := m.Response.(type) {
	case *ReflectionResponse_Reflection:
		s := proto.Size(x.Reflection)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ReflectionResponse_Error:
		s := proto.Size(x.Error)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Reflection struct {
	Service        []string `protobuf:"bytes,1,rep,name=service" json:"service,omitempty"`
	FileDescriptor [][]byte `protobuf:"bytes,2,rep,name=file_descriptor,json=fileDescriptor,proto3" json:"file_descriptor,omitempty"`
}

func (m *Reflection) Reset()                    { *m = Reflection{} }
func (m *Reflection) String() string            { return proto.CompactTextString(m) }
func (*Reflection) ProtoMessage()               {}
func (*Reflection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Error struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type InvokeRequest struct {
	Method  string `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *InvokeRequest) Reset()                    { *m = InvokeRequest{} }
func (m *InvokeRequest) String() string            { return proto.CompactTextString(m) }
func (*InvokeRequest) ProtoMessage()               {}
func (*InvokeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type InvokeResponse struct {
	// Types that are valid to be assigned to Response:
	//	*InvokeResponse_Payload
	//	*InvokeResponse_Error
	Response isInvokeResponse_Response `protobuf_oneof:"response"`
}

func (m *InvokeResponse) Reset()                    { *m = InvokeResponse{} }
func (m *InvokeResponse) String() string            { return proto.CompactTextString(m) }
func (*InvokeResponse) ProtoMessage()               {}
func (*InvokeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type isInvokeResponse_Response interface {
	isInvokeResponse_Response()
}

type InvokeResponse_Payload struct {
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3,oneof"`
}
type InvokeResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,oneof"`
}

func (*InvokeResponse_Payload) isInvokeResponse_Response() {}
func (*InvokeResponse_Error) isInvokeResponse_Response()   {}

func (m *InvokeResponse) GetResponse() isInvokeResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *InvokeResponse) GetPayload() []byte {
	if x, ok := m.GetResponse().(*InvokeResponse_Payload); ok {
		return x.Payload
	}
	return nil
}

func (m *InvokeResponse) GetError() *Error {
	if x, ok := m.GetResponse().(*InvokeResponse_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*InvokeResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _InvokeResponse_OneofMarshaler, _InvokeResponse_OneofUnmarshaler, _InvokeResponse_OneofSizer, []interface{}{
		(*InvokeResponse_Payload)(nil),
		(*InvokeResponse_Error)(nil),
	}
}

func _InvokeResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*InvokeResponse)
	// response
	switch x := m.Response.(type) {
	case *InvokeResponse_Payload:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.Payload)
	case *InvokeResponse_Error:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("InvokeResponse.Response has unexpected type %T", x)
	}
	return nil
}

func _InvokeResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*InvokeResponse)
	switch tag {
	case 1: // response.payload
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Response = &InvokeResponse_Payload{x}
		return true, err
	case 2: // response.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Error)
		err := b.DecodeMessage(msg)
		m.Response = &InvokeResponse_Error{msg}
		return true, err
	default:
		return false, nil
	}
}

func _InvokeResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*InvokeResponse)
	// response
	switch x := m.Response.(type) {
	case *InvokeResponse_Payload:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Payload)))
		n += len(x.Payload)
	case *InvokeResponse_Error:
		s := proto.Size(x.Error)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*ReflectionResponse)(nil), "ReflectionResponse")
	proto.RegisterType((*Reflection)(nil), "Reflection")
	proto.RegisterType((*Error)(nil), "Error")
	proto.RegisterType((*InvokeRequest)(nil), "InvokeRequest")
	proto.RegisterType((*InvokeResponse)(nil), "InvokeResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x29, 0x55, 0x0b, 0xbd, 0xa4, 0x45, 0xf2, 0x80, 0x22, 0x06, 0x04, 0x5e, 0xc8, 0x42,
	0x06, 0x78, 0x02, 0x2a, 0x90, 0x60, 0x42, 0xf2, 0x84, 0x58, 0xaa, 0x90, 0x5c, 0xa9, 0x45, 0x9a,
	0x33, 0x67, 0x53, 0x89, 0xb7, 0x27, 0x36, 0x4e, 0xc3, 0xca, 0xf8, 0xff, 0xfa, 0xf4, 0x9d, 0xef,
	0x0c, 0xb3, 0xd2, 0xe8, 0xc2, 0x30, 0x39, 0x92, 0x04, 0x42, 0xe1, 0xba, 0xc1, 0xca, 0x69, 0x6a,
	0x15, 0x5a, 0x43, 0xad, 0x45, 0x71, 0x0d, 0xc0, 0xfb, 0x36, 0x1b, 0x5d, 0x8c, 0xf2, 0xe4, 0x26,
	0x29, 0x06, 0xf0, 0xf1, 0x40, 0xfd, 0x01, 0xc4, 0x39, 0x4c, 0x90, 0x99, 0x38, 0x3b, 0x0c, 0xe4,
	0xb4, 0x78, 0xf0, 0xa9, 0x83, 0x7e, 0xeb, 0x25, 0xc0, 0x31, 0x47, 0xb5, 0x7c, 0x06, 0x18, 0x3c,
	0x22, 0x83, 0x23, 0x8b, 0xbc, 0xd3, 0x15, 0x76, 0x53, 0xc6, 0xf9, 0x4c, 0xf5, 0x51, 0x5c, 0xc1,
	0xc9, 0x5a, 0x37, 0xb8, 0xaa, 0xd1, 0x56, 0xac, 0x8d, 0x0b, 0xf6, 0x71, 0x9e, 0xaa, 0x85, 0xaf,
	0xef, 0xf7, 0xad, 0xbc, 0x84, 0x49, 0x18, 0xe7, 0x5d, 0x5b, 0xb4, 0xb6, 0x7c, 0xc7, 0xf0, 0xe2,
	0xce, 0x15, 0xa3, 0xbc, 0x83, 0xf9, 0x53, 0xbb, 0xa3, 0x0f, 0x54, 0xf8, 0xf9, 0x85, 0xd6, 0x89,
	0x53, 0x98, 0x6e, 0xd1, 0x6d, 0xa8, 0x8e, 0x64, 0x4c, 0x5e, 0x61, 0xca, 0xef, 0x86, 0xca, 0x3a,
	0xac, 0x92, 0xaa, 0x3e, 0xca, 0x17, 0x58, 0xf4, 0x8a, 0x78, 0xa3, 0xb3, 0x81, 0xf5, 0x92, 0xb4,
	0x5b, 0xb7, 0x2f, 0xfe, 0x73, 0x90, 0xe5, 0xfc, 0x35, 0xd9, 0x38, 0x67, 0x56, 0x7e, 0x71, 0xe4,
	0xb7, 0x69, 0xf8, 0x97, 0xdb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd2, 0xf4, 0x95, 0x19, 0xa4,
	0x01, 0x00, 0x00,
}
